name: timething

channels:
  - pytorch
  - huggingface
  - conda-forge

dependencies:
  - python=3.8
  - click
  - datasets
  - num2words
  - numpy
  - openai
  - pytorch
  - tokenizers
  - torchaudio
  - transformers=4.6.0
