name: timething

channels:
  - pytorch
  - huggingface
  - conda-forge

dependencies:
  - python=3.8
  - click
  - datasets
  - num2words
  - numpy
  - pytorch
  - tokenizers=0.10.1
  - torchaudio
  - transformers=4.4.2
